name 'cesnet-hive'
version '0.9.6'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-hive'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'Apache Hive Puppet Module'
description 'Apache Hive Puppet Module'
project_page 'https://github.com/MetaCenterCloudPuppet'

dependency 'puppetlabs/stdlib', '>= 1.0.0 <5.0.0'
dependency 'adrien/alternatives', '>= 0.3.0 <1.0.0'
dependency 'cesnet/hadoop', '>= 0.9.4 <2.0.0'
