name          'cesnet-hive'
version       '0.1.0'
source        'http://scientific.zcu.cz/git/cesnet-hive.git'
author        'František Dvořák <valtri@civ.zcu.cz>'
license       'ASL 2.0'
summary       'Apache Hive Puppet Module'
description   'Apache Hive Puppet Module'
project_page  'scientific.zcu.cz'

dependency 'puppetlabs/stdlib'
