name 'cesnet-hive'
version '0.10.0'
source 'https://github.com/MetaCenterCloudPuppet/cesnet-hive'
author 'Frantisek Dvorak <valtri@civ.zcu.cz>'
license 'MIT'
summary 'Apache Hive Puppet Module'
description 'Apache Hive Puppet Module'
project_page 'https://github.com/MetaCenterCloudPuppet'

dependency 'puppetlabs/stdlib', '>=1.0.0 <5.0.0'
dependency 'cesnet/hadoop', '>=0.9.4 <3.0.0'
dependency 'cesnet/hadoop_lib', '>=0.2.0 <1.0.0'
